PROCESS BEFORE OUTPUT.
 MODULE STATUS_0100.
LOOP at sdyn_itab into sdyn_sdw4 WITH CONTROL TABLE_CONTROL.
MODULE CHANGE_SDYN_CONN.
ENDLOOP.

*
PROCESS AFTER INPUT.
 module exit at exit-command.
 MODULE USER_COMMAND_0100.

LOOP at sdyn_itab.
MODULE READ_TABLE_CONTROL.
ENDLOOP.
