*&SPWIZARD: OUTPUT MODULE FOR TC 'TC_ITEMS'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: UPDATE LINES FOR EQUIVALENT SCROLLBAR
MODULE TC_ITEMS_CHANGE_TC_ATTR OUTPUT.
  DESCRIBE TABLE GT_ITEMS_TC LINES TC_ITEMS-lines.
ENDMODULE.