*&SPWIZARD: INPUT MODULE FOR TC 'TC_ITEMS'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: MODIFY TABLE
MODULE TC_ITEMS_MODIFY INPUT.
  MODIFY GT_ITEMS_TC
    FROM GS_ITEMS_TC
    INDEX TC_ITEMS-CURRENT_LINE.
ENDMODULE.